"""track simulation telemetry

Revision ID: 13581a9b5514
Revises: f29848246727
Create Date: 2026-10-07 01:58:44.357761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13581a9b5514'
down_revision: Union[str, Sequence[str], None] = 'f29848246727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('metric_event_ids', sa.ARRAY(sa.UUID()), nullable=False))
    op.add_column('simulation_runs', sa.Column('log_event_ids', sa.ARRAY(sa.UUID()), nullable=False))
    op.add_column('simulation_runs', sa.Column('deployment_event_ids', sa.ARRAY(sa.UUID()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'deployment_event_ids')
    op.drop_column('simulation_runs', 'log_event_ids')
    op.drop_column('simulation_runs', 'metric_event_ids')
    # ### end Alembic commands ###
