"""add database indexes

Revision ID: 205606cd9135
Revises: 807def370e1e
Create Date: 2026-09-03 13:50:10.095327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205606cd9135'
down_revision: Union[str, Sequence[str], None] = '807def370e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_evidence_items_incident_collected_at', 'evidence_items', ['incident_id', 'collected_at'], unique=False)
    op.create_index('ix_evidence_items_source', 'evidence_items', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_incidents_project_detected_at', 'incidents', ['project_id', 'detected_at'], unique=False)
    op.create_index('ix_incidents_project_status', 'incidents', ['project_id', 'status'], unique=False)
    op.create_index('ix_investigation_results_investigation', 'investigation_results', ['investigation_id'], unique=False)
    op.create_index('ix_investigations_incident_status', 'investigations', ['incident_id', 'status'], unique=False)
    op.create_index('ix_log_events_service_timestamp', 'log_events', ['service_id', 'timestamp'], unique=False)
    op.create_index('ix_metric_events_service_name_timestamp', 'metric_events', ['service_id', 'name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_events_service_name_timestamp', table_name='metric_events')
    op.drop_index('ix_log_events_service_timestamp', table_name='log_events')
    op.drop_index('ix_investigations_incident_status', table_name='investigations')
    op.drop_index('ix_investigation_results_investigation', table_name='investigation_results')
    op.drop_index('ix_incidents_project_status', table_name='incidents')
    op.drop_index('ix_incidents_project_detected_at', table_name='incidents')
    op.drop_index('ix_evidence_items_source', table_name='evidence_items')
    op.drop_index('ix_evidence_items_incident_collected_at', table_name='evidence_items')
    # ### end Alembic commands ###
