"""add historical incident embeddings

Revision ID: 9fe2411f05aa
Revises: 615252e2296a
Create Date: 2026-09-17 22:44:01.155234

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe2411f05aa'
down_revision: Union[str, Sequence[str], None] = '615252e2296a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_incident_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('historical_incident_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['historical_incident_id'], ['historical_incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('historical_incident_id', name='uq_historical_incident_embeddings_incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_incident_embeddings')
    # ### end Alembic commands ###
